### ISSUE TITLE
Cannot read property 'encoding' of undefined

### ISSUE THREAD

**Issue by ghost** [bnoguchi/redis-node#12]
Node v0.2.6, Redis version 2.1.4.

node.js:63
    throw e;
    ^
TypeError: Cannot read property 'encoding' of undefined
    at Object.<anonymous> (/usr/local/lib/node/.npm/redis-node/0.2.8/package/lib/command.js:38:73)
    at Client.sendCommand (/usr/local/lib/node/.npm/redis-node/0.2.8/package/lib/client.js:436:19)
    at Client.get (/usr/local/lib/node/.npm/redis-node/0.2.8/package/lib/client.js:373:14)
    at Object.<anonymous> (/home/node/rotocj/servers/import-redis.js:29:9)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at Object.runMain (node.js:522:24)
    at Array.<anonymous> (node.js:756:12)
    at EventEmitter._tickCallback (node.js:55:22)

**Comment by bnoguchi** [comment]
What's on L29 on import-redis.js?

**Comment by ghost** [comment]
There is:
rclient.on('error', function(err) {
    console.log('Error ' + err);
});
And after:
rclient.hget('cs', domain, function(id) {
 console.log(id);
 rclient.close();
});

**Comment by bnoguchi** [comment]
console.log(domain) before rclient.hget.
I think it may be undefined, in which case therein lies the cause of the error.
Let me know if this is or isn't the case.

**Comment by bnoguchi** [comment]
Closed
