### ISSUE TITLE
Cannot read property 'commandName' of undefined

### ISSUE THREAD

**Issue by ghost** [bnoguchi/redis-node#20]
Hi, sorry for disturbing but i have been searching quit a lot to fix that issue but couldn't find any solution. Here is my problem :
I'm using redis has a communication layer, which means I am only using the pub/sub system. My code seems to be relativly good, well at least there is no known bug, and sometimes, completly without reason, i have a" Cannot read property 'commandName' of undefined" error, where undefined is supposed to be commandForReply in file /lib/client.js ligne278.
This error has been poping out relatively often and it's really annoying because I can't find any reason in my code, so I thought maybe there is a known problem or so in the library.

Hope someone could help me, 

Lou-adrien

**Comment by ghost** [comment]
Here is the full stacktrace for more info : 

Cannot read property 'commandName' of undefined
TypeError: Cannot read property 'commandName' of undefined
    at Client.handleReply (/home/lou/node_modules/redis-node/lib/client.js:278:38)
    at Client.<anonymous> (native)
    at Client.emit (events.js:64:17)
    at Client.handleData (/home/lou/node_modules/redis-node/lib/client.js:249:18)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:678:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)

and also :
node : 0.4.8
redis node : last one on git
Redis server version 2.0.1
